# Análisis de Datos de un Sensor de Temperatura

### Tenemos datos de temperatura registrados cada hora en diferentes sensores durante una semana. Usaremos NumPy para:

### - Generar datos aleatorios de temperatura.
### - Aplanar los arreglos para facilitar análisis.
### - Concatenar datos de diferentes sensores.
### - Cambiar la forma para organizar los datos por días.
### - Aplicar indexación y slicing para extraer información.
### - Manejar tipos de datos.

## 1. Generar datos aleatorios

Generamos datos de temperatura simulados para 3 sensores durante una semana (7 días, 24 horas por día).

In [ ]:

import numpy as np
import random
# Fijar semilla para reproducibilidad
np.random.seed(42)
# Generar datos aleatorios de temperatura (en °C) para 3 sensores (7 días x 24 horas)
sensor_1 = np.random.uniform(low=16.0, high=34.0, size=(7, 24))
sensor_2 = np.random.uniform(low=16.0, high=34.0, size=(7, 24))
sensor_3 = np.random.uniform(low=16.0, high=34.0, size=(7, 24))
# Mostrar una muestra de datos del primeri día
print("Datos del primer día para el sensor 1:")
print(sensor_1[0])


Datos del primer día para el sensor 1:
[22.74172214 33.11285752 29.17589095 26.77585272 18.80833553 18.80790137
 17.04550502 31.59117062 26.82007021 28.7453064  16.3705209  33.45837734
 30.98396753 19.82210399 19.27284941 19.30128118 21.47636037 25.44561577
 23.77501034 21.24212452 27.01335211 18.51088949 21.25860367 22.59451318]


## 2. Aplanar los datos

Convertir la matriz de (7,24) en un arreglo de 168 valores (7 días x 24 horas).

In [ ]:

# sensor_1_flat = sensor_1.ravel()
sensor_1_flat = sensor_1.ravel()

print("Datos aplanados del sensor 1:")
print(sensor_1_flat)


Datos aplanados del sensor 1:
[22.74172214 33.11285752 29.17589095 26.77585272 18.80833553 18.80790137
 17.04550502 31.59117062 26.82007021 28.7453064  16.3705209  33.45837734
 30.98396753 19.82210399 19.27284941 19.30128118 21.47636037 25.44561577
 23.77501034 21.24212452 27.01335211 18.51088949 21.25860367 22.59451318
 24.20925972 30.13316731 19.59412808 25.25621989 26.66346224 16.83610743
 26.93580733 19.06943423 17.17092867 33.07993967 33.3813766  30.55115227
 21.48304785 17.75809805 28.31619448 23.92274489 18.19668823 24.91318438
 16.61899338 32.36776724 20.65803967 27.92540112 21.61079937 25.36122438
 25.84078503 19.3273802  33.4525233  29.95239082 32.91098095 32.10689231
 26.76219962 32.59373623 17.59286504 19.52769152 16.8140912  21.85594595
 22.99619121 20.88428257 30.91727516 22.42155988 21.05682117 25.7685295
 18.53663605 30.43954565 17.34191159 33.76396486 29.90040585 19.57688227
 16.09939811 30.67830571 28.72343219 29.12212902 29.88286624 17.33280373
 22.45238311 18.085643

## 3. Concatenar los datos de los sensores

Juntamos los datos de los 3 sensores para tener una matriz más grande.


In [ ]:
# datos_concatenados = np.concatenate((sensor_1_flat, sensor_2.flatten(), sensor_3.flatten()))
datos_concatenados = np.concatenate((sensor_1_flat, sensor_2.flatten(), sensor_3.flatten()))

print("Datos concatenados de los 3 sensores:")
print(datos_concatenados)


Datos concatenados de los 3 sensores:
[22.74172214 33.11285752 29.17589095 26.77585272 18.80833553 18.80790137
 17.04550502 31.59117062 26.82007021 28.7453064  16.3705209  33.45837734
 30.98396753 19.82210399 19.27284941 19.30128118 21.47636037 25.44561577
 23.77501034 21.24212452 27.01335211 18.51088949 21.25860367 22.59451318
 24.20925972 30.13316731 19.59412808 25.25621989 26.66346224 16.83610743
 26.93580733 19.06943423 17.17092867 33.07993967 33.3813766  30.55115227
 21.48304785 17.75809805 28.31619448 23.92274489 18.19668823 24.91318438
 16.61899338 32.36776724 20.65803967 27.92540112 21.61079937 25.36122438
 25.84078503 19.3273802  33.4525233  29.95239082 32.91098095 32.10689231
 26.76219962 32.59373623 17.59286504 19.52769152 16.8140912  21.85594595
 22.99619121 20.88428257 30.91727516 22.42155988 21.05682117 25.7685295
 18.53663605 30.43954565 17.34191159 33.76396486 29.90040585 19.57688227
 16.09939811 30.67830571 28.72343219 29.12212902 29.88286624 17.33280373
 22.45238311 1

## 4. Cambiar la forma de los datos

Reorganizamos los datos en una matriz de (7 días, 24 horas, 3 sensores) para facilitar el análisis.

In [ ]:

# Mostrar del primer dia, las primeras dos horas de los 3 sensores
# Cambiar la forma de los datos concatenados
datos_reshaped = datos_concatenados.reshape(7, 24, 3)

# Mostrar del primer día, las primeras dos horas de los 3 sensores
print("Datos del primer día, primeras dos horas para los 3 sensores:")
print(datos_reshaped[0, :2, :])



Datos del primer día, primeras dos horas para los 3 sensores:
[[22.74172214 33.11285752 29.17589095]
 [26.77585272 18.80833553 18.80790137]]


## 5. Indexación y slicing

Extraer información especifica

In [ ]:
# Temperatura del sensor 2, día 3, hora 12
temp_sensor_2_dia_3_hora_12 = datos_reshaped[2, 11, 1]
print("Temperatura del sensor 2, día 3, hora 12:", temp_sensor_2_dia_3_hora_12)

# Datos del día 5 para todos los sensores
datos_dia_5 = datos_reshaped[4, :, :]
print("Datos del día 5 para todos los sensores:")
print(datos_dia_5)


Temperatura del sensor 2, día 3, hora 12: 32.86113979726122
Datos del día 5 para todos los sensores:
[[21.15774254 26.63499869 16.5490045 ]
 [16.6722674  30.80681009 22.48343155]
 [18.28708923 25.40037868 29.85988396]
 [19.88477849 27.21202856 17.53625437]
 [16.93027098 25.56438337 25.73143219]
 [27.47373823 29.06964401 33.56533743]
 [25.29340627 21.81321651 30.31335151]
 [20.87498052 23.90148557 17.41221486]
 [16.45631338 33.32767146 31.04764217]
 [28.52753571 23.361153   19.11929776]
 [18.81586677 20.50437217 25.88607996]
 [28.86272661 27.88355278 21.03881015]
 [33.18757505 29.2821445  25.97837295]
 [27.01097343 23.55280112 20.45915781]
 [22.40750822 29.64122999 16.2590828 ]
 [18.08930753 16.82804756 16.73311844]
 [31.39829051 28.66584147 24.53512892]
 [17.76101489 24.84908575 24.52249187]
 [19.11763366 23.80932969 23.17308522]
 [27.08530176 27.43168572 16.81547218]
 [22.74302706 27.26547848 25.05645265]
 [31.41681714 27.85648537 18.93281969]
 [17.27023745 27.56354701 16.47720359]
 [

## 6. Convertir tipos de datos

Para ahorrar memoria, convertimos los datos de float64 a float32



In [ ]:
datos_reshaped_float32 = datos_reshaped.astype(np.float32)

print("Datos convertidos a float32:")
print(datos_reshaped_float32)


Datos convertidos a float32:
[[[22.741722 33.112858 29.175892]
  [26.775852 18.808336 18.807901]
  [17.045506 31.591171 26.82007 ]
  [28.745306 16.370522 33.458378]
  [30.983967 19.822104 19.27285 ]
  [19.301281 21.47636  25.445616]
  [23.775011 21.242125 27.013351]
  [18.51089  21.258604 22.594513]
  [24.209259 30.133167 19.594128]
  [25.25622  26.663462 16.836107]
  [26.935808 19.069435 17.170929]
  [33.07994  33.38138  30.551153]
  [21.483047 17.758099 28.316195]
  [23.922745 18.196688 24.913185]
  [16.618994 32.367767 20.65804 ]
  [27.925402 21.6108   25.361225]
  [25.840786 19.327381 33.452522]
  [29.95239  32.91098  32.10689 ]
  [26.7622   32.593735 17.592865]
  [19.52769  16.81409  21.855946]
  [22.996191 20.884283 30.917274]
  [22.42156  21.056822 25.76853 ]
  [18.536636 30.439547 17.341911]
  [33.763966 29.900406 19.576881]]

 [[16.099398 30.678307 28.723433]
  [29.12213  29.882866 17.332804]
  [22.452383 18.085644 31.535862]
  [27.219366 21.956165 17.14405 ]
  [21.597681 21.8